name: api
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  amplify_auth_cognito_dart: ^0.11.3
  amplify_core: ^2.3.0
  amplify_secure_storage_dart: ^0.5.1
  amplify_user_repository:
    path:
      packages/amplify_user_repository
  dart_frog: ^1.0.0
  dart_frog_auth: ^1.1.0

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
